### ISSUE TITLE
Minify fails on JS with arrow function expression

### ISSUE THREAD

**Issue by jepsar** [Chris2011/js-css-minify-compress#44] opened 2019-02-07 10:56 UTC
For example

````
function resolveAfter2Seconds() {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve('resolved');
    }, 2000);
  });
}

async function asyncCall() {
  console.log('calling');
  var result = await resolveAfter2Seconds();
  console.log(result);
  // expected output: 'resolved'
}

asyncCall();
````

**Comment by Chris2011** [comment] 2019-02-07 13:05
Hi, first please read the readme. Second, this is almost a duplicate of #3.

**Closed by Chris2011** 2019-02-07 13:05 UTC
